# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest
variables:
- group: Heco-test-linkedkeyvault
- name: my-passed-variable
  value: $[variables.mysecret] # uses runtime expression

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world' > test1.txt
    workingDirectory: '$(Pipeline.Workspace)'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo '$(mysecret)' > test2.txt
    workingDirectory: '$(Pipeline.Workspace)'
#- script: "echo $(mysecret) | secret1.txt" # uses macro syntax
#- script: "echo $(my-passed-variable) > $(Pipeline.Workspace)/secret2.txt"
- pwsh: |
    ls $(Pipeline.Workspace)
    $alias = Get-ChildItem $(Pipeline.Workspace) | ? { $_.Name.Length -gt 1 } | select -ExpandProperty Name -First 1
    echo "##vso[task.setvariable variable=ArtifactAlias]$alias"
    displayName: 'determine artifact pipeline alias'

#- pwsh: echo 'alias: $(ArtifactAlias)' 
- task: PowerShell@2
  displayName: '[Debug] Output ARM templates that will be deployed'
  inputs:
      targetType: inline
      script: |
        $files = Get-ChildItem -Path $(Pipeline.Workspace)\*.tst
        foreach ($file in $files)
        {
          Write-Host "=== ARM template Output ==="
          Write-Host "Filename: ($file)" 
          $content = Get-Content $file
          Write-Host $content
        }
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      ls
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'drop'
    publishLocation: 'pipeline'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
 
- task: azurekeyvaultactions@2
  inputs:
    ConnectedServiceName: 'Trainingdevopsyamlserviceconn'
    Action: 'GetSecret'
    KeyVaultName: 'dev-devops-demo-keyvault'
    SecretName: 'EncryptionKey'
    VariableName: 'thesecret'
- task: cboroson-WriteSecrets@1
  inputs:
    ConnectedServiceName: 'Trainingdevopsyamlserviceconn'
    resourceGroupName: 'yaml-introduction-demo'
    KeyVaultName: 'dev-we-devops-keyvault'
    SecretName: 'EncryptionKey'
    SecretValue: $(thesecret)