#parameters:


stages:
- stage: Deploy_DEV
  displayName: 'Deploy to DEV'
  dependsOn: Build
  variables:
   - name: environment
     value: DEV
   - name: serviceConnection
     value: 'TrainingAccountSP'
   - group: Yaml_Introduction.Infra.Dev

  jobs:
    - template: release-template-steps.yml
      parameters: 
        Environment: ${{ variables.environment }}
        AzureServiceConnectionName: ${{ variables.serviceConnection }}