parameters:
  Environment: ''
  AzureServiceConnectionName: ''
  PoolName: 'Hosted VS2017'

jobs:
  - deployment: Infra_Deployment
    displayName: 'Deploy Infra Resources'
    pool:
      name: ${{ parameters.PoolName }}
    environment: ${{ parameters.Environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: qetza.replacetokens.replacetokens-task.replacetokens@3
              displayName: 'Replace tokens'
              inputs:
                rootDirectory: '$(Pipeline.Workspace)'
                targetFiles: |
                 **/*.json
                 **/*.ps1
                escapeType: none
                actionOnMissing: fail

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy Storage Account'
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                resourceGroupName: '$(Infra.ResourceGroup.Name)'
                location: '$(Infra.Location.Primary)'
                csmFile: '$(Pipeline.Workspace)/Resources/storage.json'
                csmParametersFile: '$(Pipeline.Workspace)/Resources/storage.parameters.json'
                deploymentOutputs: ArmOutputs

            - task: PowerShell@2
              displayName: 'Update Variable Group - Storage Account'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/Scripts/AzureDevops-WriteArmOutputsToVariableGroup.ps1'
                arguments: '-variableGroupName $(Infra.VariableGroup.Name)'
            

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy App Service Plan'
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                resourceGroupName: '$(Infra.ResourceGroup.Name)'
                location: '$(Infra.Location.Primary)'
                csmFile: '$(Pipeline.Workspace)/Resources/app-service-plan.json'
                csmParametersFile: '$(Pipeline.Workspace)/Resources/app-service-plan.parameters.json'
                deploymentOutputs: ArmOutputs

            - task: PowerShell@2
              displayName: 'Update Variable Group - App Service Plan'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/Scripts/AzureDevops-WriteArmOutputsToVariableGroup.ps1'
                arguments: '-variableGroupName $(Infra.VariableGroup.Name)'

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy Key Vault'
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                resourceGroupName: '$(Infra.ResourceGroup.Name)'
                location: '$(Infra.Location.Primary)'
                csmFile: '$(Pipeline.Workspace)/Resources/key-vault.json'
                csmParametersFile: '$(Pipeline.Workspace)/Resources/key-vault.parameters.json'
                deploymentOutputs: ArmOutputs

            - task: PowerShell@2
              displayName: 'Update Variable Group - Key Vault'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/Scripts/AzureDevops-WriteArmOutputsToVariableGroup.ps1'
                arguments: '-variableGroupName $(Infra.VariableGroup.Name)'

            - task: AzurePowerShell@3
              displayName: 'Remove Old ARM Deployments'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                ScriptPath: '$(Pipeline.Workspace)/Scripts/Azure-RemoveOldArmDeployments.ps1'
                ScriptArguments: '-resourceGroup $(Infra.ResourceGroup.Name)'
                azurePowerShellVersion: LatestVersion