name: 1.0.$(Rev:r)
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Resource Collection
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    clean: true
  - task: CopyFiles@2
    displayName: Copy ARM Templates
    inputs:
      SourceFolder: src/Infrastructure/Yaml_Introduction.Infra/Templates
      Contents: >-
        *.json

        !**local**
      TargetFolder: $(Build.ArtifactStagingDirectory)\Templates
  - task: PublishBuildArtifacts@1
    displayName: Publish ARM Templates
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)\Templates
      ArtifactName: Resources
  - task: PublishBuildArtifacts@1
    displayName: Publish Scripts
    inputs:
      PathtoPublish: deploy/scripts
      ArtifactName: Scripts
...
