# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  projectPath: '**/DevOpsSample.WebApp'

stages:
- stage: build
  jobs:
  - job: run_build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Copy arm templates'
      inputs:
        contents: '**/deploy/*.json'
        targetFolder: '$(Build.ArtifactStagingDirectory)/arm'
    - task: CopyFiles@2
      displayName: 'Copy sql scripts'
      inputs:
        contents: '**/deploy/scripts/*.sql'
        targetFolder: '$(Build.ArtifactStagingDirectory)/scripts'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
- stage: deploy
  dependsOn: build
  jobs:
  - job: run_deploy_apps
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        path: '$(Pipeline.Workspace)'
    - task: Bash@3
      inputs:
         targetType: 'inline'
         script: |
           # Write your commands here           
           ls -lha
  - job: run_deploy_sql
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'TrainingAccountSP'
        subscriptionId: '533f6b10-3a70-4c5d-8962-8b51e839a13c'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'aca-devops'
        location: 'West Europe'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/arm/**/sql-deploy.json'
        deploymentMode: 'Incremental'
    - task: SqlDacpacDeploymentOnMachineGroup@0
      inputs:
        TaskType: 'sqlQuery'
        SqlFile: '$(Pipeline.Workspace)/scripts/**/PopulateSqlDb.sql'
        ServerName: 'demo-sqlsvr-training.database.windows.net'
        DatabaseName: 'demo-sqldb-training'
        AuthScheme: 'sqlServerAuthentication'
        SqlUsername: 'sqladmin'
        SqlPassword: '$(sqlPwd)'