parameters:
  Environment: ''
  AzureServiceConnectionName: ''

jobs:
  - deployment: App_Deployment
    displayName: 'Deploy App Resources'
    pool:
      vmImage: windows-latest
    environment: ${{ parameters.Environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: qetza.replacetokens.replacetokens-task.replacetokens@3
              displayName: 'Replace tokens'
              inputs:
                rootDirectory: '$(Pipeline.Workspace)'
                targetFiles: |
                 **/*.json
                 **/*.ps1
                escapeType: none
                actionOnMissing: fail

            - task: AzureResourceGroupDeployment@2
              displayName: 'Deploy App Service'
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                resourceGroupName: '$(Infra.ResourceGroup.Name)'
                location: '$(Infra.Location.Primary)'
                csmFile: '$(Pipeline.Workspace)/Resources/app-service.json'
                csmParametersFile: '$(Pipeline.Workspace)/Resources/app-service.parameters.json'
                deploymentOutputs: ArmOutputs

            - task: PowerShell@2
              displayName: 'Update Variable Group - App Service'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/Scripts/AzureDevops-WriteArmOutputsToVariableGroup.ps1'
                arguments: '-variableGroupName $(Infra.VariableGroup.Name)'
           
            - task: AzureRmWebAppDeployment@4
              displayName: 'Deploy App'
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                WebAppName: '$(Infra.AppService.Name)'
                packageForLinux: '$(Pipeline.Workspace)/Api/publish.zip'

            - task: AzurePowerShell@3
              displayName: 'Remove Old ARM Deployments'
              env:
                SYSTEM_ACCESSTOKEN: $(System.AccessToken) 
              inputs:
                azureSubscription: ${{ parameters.AzureServiceConnectionName }}
                ScriptPath: '$(Pipeline.Workspace)/Scripts/Azure-RemoveOldArmDeployments.ps1'
                ScriptArguments: '-resourceGroup $(Infra.ResourceGroup.Name)'
                azurePowerShellVersion: LatestVersion